In [1]:
# beta 8.0.1
import pickle

for i in range(1, 38):
    file_path = "./log/" + str(i) + "first.pickle"
    with open(file_path, 'rb') as f:
        data = pickle.load(f)
    print(data.keys())
    #path = "/Users/peggy/Documents/109-2(2-2)/Introduction to machine learning and its application to gaming/MLGame/games/arkanoid/log/" + str(i) + "first.pickle"
   

#file = open(path, "rb")

#file_path = './log/1first.pickle'
#with open(file_path, 'rb') as f:
    #data = pickle.load(f)

#print(data.keys())

dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys(['record_format_version', 'ml'])
dict_keys([

In [2]:
data['ml'].keys()

dict_keys(['scene_info', 'command'])

In [3]:
data['ml']['scene_info']

[{'frame': 0,
  'status': 'GAME_ALIVE',
  'ball': (93, 395),
  'platform': (75, 400),
  'bricks': [(0, 100),
   (175, 100),
   (0, 110),
   (25, 110),
   (150, 110),
   (175, 110),
   (0, 120),
   (25, 120),
   (150, 120),
   (175, 120),
   (0, 130),
   (25, 130),
   (150, 130),
   (175, 130),
   (0, 140),
   (25, 140),
   (150, 140),
   (175, 140),
   (0, 150),
   (25, 150),
   (150, 150),
   (175, 150),
   (0, 160),
   (25, 160),
   (150, 160),
   (175, 160),
   (0, 170),
   (25, 170),
   (150, 170),
   (175, 170),
   (0, 180),
   (25, 180),
   (150, 180),
   (175, 180),
   (0, 190),
   (25, 190),
   (150, 190),
   (175, 190),
   (0, 200),
   (25, 200),
   (150, 200),
   (175, 200),
   (0, 210),
   (25, 210),
   (150, 210),
   (175, 210),
   (0, 220),
   (25, 220),
   (150, 220),
   (175, 220),
   (0, 230),
   (25, 230),
   (150, 230),
   (175, 230),
   (0, 240),
   (25, 240),
   (150, 240),
   (175, 240),
   (0, 250),
   (25, 250),
   (150, 250),
   (175, 250),
   (0, 260),
   (25, 

In [4]:
data['ml']['command']

['SERVE_TO_RIGHT',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 'NONE',
 None,
 None,
 None,
 None,
 None,
 None,
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 'MOVE_RIGHT',
 None]

In [5]:
data['ml']['scene_info'][0], data['ml']['command'][-0]

({'frame': 0,
  'status': 'GAME_ALIVE',
  'ball': (93, 395),
  'platform': (75, 400),
  'bricks': [(0, 100),
   (175, 100),
   (0, 110),
   (25, 110),
   (150, 110),
   (175, 110),
   (0, 120),
   (25, 120),
   (150, 120),
   (175, 120),
   (0, 130),
   (25, 130),
   (150, 130),
   (175, 130),
   (0, 140),
   (25, 140),
   (150, 140),
   (175, 140),
   (0, 150),
   (25, 150),
   (150, 150),
   (175, 150),
   (0, 160),
   (25, 160),
   (150, 160),
   (175, 160),
   (0, 170),
   (25, 170),
   (150, 170),
   (175, 170),
   (0, 180),
   (25, 180),
   (150, 180),
   (175, 180),
   (0, 190),
   (25, 190),
   (150, 190),
   (175, 190),
   (0, 200),
   (25, 200),
   (150, 200),
   (175, 200),
   (0, 210),
   (25, 210),
   (150, 210),
   (175, 210),
   (0, 220),
   (25, 220),
   (150, 220),
   (175, 220),
   (0, 230),
   (25, 230),
   (150, 230),
   (175, 230),
   (0, 240),
   (25, 240),
   (150, 240),
   (175, 240),
   (0, 250),
   (25, 250),
   (150, 250),
   (175, 250),
   (0, 260),
   (25, 

In [6]:
# 提取特徵

scene_info = data['ml']['scene_info']
command = data['ml']['command']

Ball_x = []
Ball_y = []
Ball_speed_x = []
Ball_speed_y = []
Direction = []
Platform = []
Command = []

for i, s in enumerate(scene_info[1:-2]):
    Ball_x.append(s['ball'][0])
    Ball_y.append(s['ball'][1])
    Platform.append(s['platform'][0])
    Ball_speed_x.append(scene_info[i+2]["ball"][0] - scene_info[i+1]["ball"][0])
    Ball_speed_y.append(scene_info[i+2]["ball"][1] - scene_info[i+1]["ball"][1])
    if Ball_speed_x[-1] > 0:
        if Ball_speed_y[-1] > 0:
            # 右下
            Direction.append(0)
        else:
            # 右上
            Direction.append(1)
    else:
        if Ball_speed_y[-1] > 0:
            # 左下
            Direction.append(2)
        else:
            # 左上
            Direction.append(3)
            
for c in command[1:-2]:
    if c == "NONE":
        Command.append(0)
    elif c == "MOVE_LEFT":
        Command.append(-1)
    elif c == "MOVE_RIGHT":
        Command.append(1)

In [7]:
import numpy as np

numpy_data = np.array([Ball_x, Ball_y, Ball_speed_x, Ball_speed_y, Direction, Platform])
X = np.transpose(numpy_data) 
y = command

In [8]:
X, y

(array([[ 93, 395,   7,  -7,   1,  75],
        [100, 388,   7,  -7,   1,  75],
        [107, 381,   7,  -7,   1,  75],
        [114, 374,   7,  -7,   1,  75],
        [121, 367,   7,  -7,   1,  75],
        [128, 360,   7,  -7,   1,  75],
        [135, 353,   7,  -7,   1,  75],
        [142, 346,   7,  -6,   1,  75],
        [149, 340,   7,   7,   0,  75],
        [156, 347,   7,   7,   0,  75],
        [163, 354,   7,   7,   0,  75],
        [170, 361,   7,   7,   0,  75],
        [177, 368,   7,   7,   0,  75],
        [184, 375,   7,   7,   0,  75],
        [191, 382,   4,   7,   0,  75],
        [195, 389,  -7,   7,   2,  75],
        [188, 396,  -7,   7,   2,  80]]),
 ['SERVE_TO_RIGHT',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  'NONE',
  None,
  None,
  None,
  None,
  None,
  None,
  'MOVE_RIGHT',
  'MOVE_RIGHT',
  'MOVE_RIGHT',
  None])

In [9]:
# 提取特徵
import numpy as np

scene_info = data['ml']['scene_info']
command = data['ml']['command']

k = range(1, len(scene_info)-1)

ball_x = np.array([scene_info[i]['ball'][0] for i in k])
ball_y = np.array([scene_info[i]['ball'][1] for i in k])
ball_speed_x = np.array([scene_info[i+1]['ball'][0] - scene_info[i]['ball'][0] for i in k])
ball_speed_y = np.array([scene_info[i+1]['ball'][1] - scene_info[i]['ball'][1] for i in k])
direction = np.where(np.vstack((ball_speed_x, ball_speed_y)) > 0, [[1],[0]], [[2],[3]]).sum(axis=0)  # x y: ++1, +-4, -+2, --3
platform = np.array([scene_info[i]['platform'][0] for i in k])
target = np.where(np.array(command) == 'NONE', 0,
                  np.where(np.array(command) == 'MOVE_LEFT', -1, 1))[1:-1]  # [0] SERVE_TO_RIGHT, [1897] None


In [10]:
# 也可以使用 pandas
X = np.hstack((ball_x.reshape(-1, 1),
               ball_y.reshape(-1, 1),
               ball_speed_x.reshape(-1, 1),
               ball_speed_y.reshape(-1, 1),
               direction.reshape(-1, 1),
               platform.reshape(-1, 1)))
y = target

In [11]:
X, y

(array([[ 93, 395,   7,  -7,   4,  75],
        [100, 388,   7,  -7,   4,  75],
        [107, 381,   7,  -7,   4,  75],
        [114, 374,   7,  -7,   4,  75],
        [121, 367,   7,  -7,   4,  75],
        [128, 360,   7,  -7,   4,  75],
        [135, 353,   7,  -7,   4,  75],
        [142, 346,   7,  -6,   4,  75],
        [149, 340,   7,   7,   1,  75],
        [156, 347,   7,   7,   1,  75],
        [163, 354,   7,   7,   1,  75],
        [170, 361,   7,   7,   1,  75],
        [177, 368,   7,   7,   1,  75],
        [184, 375,   7,   7,   1,  75],
        [191, 382,   4,   7,   1,  75],
        [195, 389,  -7,   7,   2,  75],
        [188, 396,  -7,   7,   2,  80],
        [181, 403,  -7,   7,   2,  85]]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

In [12]:
# train data
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=3)
print(model.fit(X, y))
print(model.score(X, y))

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')
1.0


In [13]:
with open('my_model.pickle', 'wb') as f:
    pickle.dump(model, f)